import { useEffect, useState } from 'react'
import { CalendarDays, Clock3, CreditCard, ShieldCheck } from 'lucide-react'
import { ApiFailure, api, type ReservationChangePayment } from '../lib/api'
import { captureReservationChangePaymentToken } from '../lib/reservation-change-payment-session'

type Props = { locale?: 'ko' | 'en' }
const copy = {
  ko: { kicker: '예약 변경 추가 결제', title: '변경 내용을 확인해 주세요', loading: '안전한 결제 정보를 불러오는 중입니다.', failure: '결제 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.', confirmed: '결제가 확인되었습니다', pending: '결제 대기 중', applying: '예약 변경을 최종 반영하고 있습니다.', number: '예약 번호', dates: '변경 일정', room: '객실 · 요금', expires: '결제 링크 만료', total: '추가 결제 금액', preparing: '결제 화면을 준비하는 중…', pay: '결제하기', note: '결제 금액과 예약 변경 확정은 호텔 서버에서 검증합니다. 카드 정보는 이 화면에 저장되지 않습니다.' },
  en: { kicker: 'RESERVATION CHANGE PAYMENT', title: 'Review your change', loading: 'Loading your secure payment details.', failure: 'We could not load your payment details. Please try again shortly.', confirmed: 'Payment confirmed', pending: 'Payment pending', applying: 'We are applying your reservation change.', number: 'Reservation number', dates: 'Changed stay dates', room: 'Room · rate', expires: 'Payment link expires', total: 'Additional payment', preparing: 'Preparing payment…', pay: 'Pay now', note: 'The hotel server verifies the payment amount and reservation change. Card details are not stored on this page.' },
} as const
function formatMoney(value: number, currency: string, locale: 'ko' | 'en') { return new Intl.NumberFormat(locale === 'en' ? 'en-US' : 'ko-KR', { style: 'currency', currency, maximumFractionDigits: 0 }).format(value) }
function formatDate(value: string, locale: 'ko' | 'en', withTime = false) { return new Intl.DateTimeFormat(locale === 'en' ? 'en-US' : 'ko-KR', { year: 'numeric', month: 'long', day: 'numeric', ...(withTime ? { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Seoul' } : { timeZone: 'UTC' }) }).format(new Date(withTime ? value : `${value}T12:00:00Z`)) }

export function ReservationChangePaymentPage({ locale = 'ko' }: Props) {
  const text = copy[locale]
  const [token] = useState(() => captureReservationChangePaymentToken(window.location, path => window.history.replaceState({}, '', path)))
  const [payment, setPayment] = useState<ReservationChangePayment | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  useEffect(() => { let active = true; async function load() { try { if (token) await api.exchangeReservationChangePaymentToken(token); const current = await api.reservationChangePayment(); if (active) setPayment(current) } catch (cause) { if (active) setError(cause instanceof ApiFailure ? cause.message : text.failure) } finally { if (active) setLoading(false) } } void load(); return () => { active = false } }, [token, text.failure])
  async function checkout() { setBusy(true); setError(''); try { const result = await api.reservationChangeCheckout(); window.location.assign(result.checkoutUrl) } catch (cause) { setError(cause instanceof ApiFailure ? cause.message : text.failure); setBusy(false) } }
  const canPay = payment?.status === 'AWAITING_PAYMENT'; const completed = payment?.status === 'READY_TO_APPLY' || payment?.status === 'APPLYING' || payment?.status === 'COMPLETED'
  return <main className="change-payment-shell"><section className="change-payment-card" aria-labelledby="change-payment-title"><header className="change-payment-header"><span className="change-payment-mark" aria-hidden="true"><ShieldCheck size={24} /></span><div><p>{text.kicker}</p><h1 id="change-payment-title">{text.title}</h1></div></header>{loading && <div className="change-payment-state" role="status">{text.loading}</div>}{error && <div className="change-payment-state is-error" role="alert">{error}</div>}{!loading && payment && <><div className={`change-payment-status ${completed ? 'is-complete' : ''}`} role="status"><strong>{completed ? text.confirmed : text.pending}</strong><span>{completed ? text.applying : payment.environmentLabel}</span></div><dl className="change-payment-details"><div><dt>{text.number}</dt><dd>•••• {payment.reservationNumberSuffix}</dd></div><div><dt><CalendarDays size={17} aria-hidden="true" /> {text.dates}</dt><dd>{formatDate(payment.checkIn, locale)} – {formatDate(payment.checkOut, locale)}</dd></div><div><dt>{text.room}</dt><dd>{payment.roomTypeName}<span>{payment.ratePlanName}</span></dd></div><div><dt><Clock3 size={17} aria-hidden="true" /> {text.expires}</dt><dd>{formatDate(payment.expiresAt, locale, true)}</dd></div></dl><div className="change-payment-total"><span>{text.total}</span><strong>{formatMoney(payment.additionalAmountKrw, payment.currency, locale)}</strong></div>{canPay && <button className="change-payment-action" type="button" onClick={checkout} disabled={busy}><CreditCard size={19} aria-hidden="true" />{busy ? text.preparing : `${formatMoney(payment.additionalAmountKrw, payment.currency, locale)} ${text.pay}`}</button>}<p className="change-payment-note">{text.note}</p></>}</section></main>
}
