type Locale = 'ko' | 'en'
const english: Record<string, string> = {
  '객실 확보 시간이 만료되어 예약이 확정되지 않았습니다. 객실을 다시 검색해 주세요.': 'The room hold expired before confirmation. Please search for rooms again.',
  '결제가 승인되지 않았습니다. 예약 확보 상태를 확인해 주세요.': 'Payment was not approved. Please check the reservation hold status.',
  '결제 결과를 확인 중입니다. 중복 결제하지 말고 서버 상태를 다시 확인해 주세요.': 'Your payment result is being checked. Check the server status before making another payment.',

  "박 · 세금 포함": " nights · tax included",
  "객실 선택": "Choose a room",
  "예약 정보": "Guest details",
  "결제": "Payment",
  "예약 조회": "My reservations",
  "예약 진행 단계": "Booking progress",
  "선택한 숙박 조건": "Selected stay",
  "객실 정보를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.": "We could not load rooms. Please try again shortly.",
  "선택한 지점": "Selected hotel",
  "예약 가능한 객실": "Available rooms",
  "표시 금액은 전체 숙박 기간의 서버 계산 총액입니다.": "Prices are the server-calculated total for your whole stay.",
  "검색 조건 수정": "Edit search",
  "예약 검색 조건": "Room search criteria",
  "조건 적용": "Apply search",
  "판매 가능 객실을 확인하고 있습니다…": "Checking available rooms…",
  "개 객실 유형을 찾았습니다.": " room types found.",
  "예약 가능한 객실이 없습니다": "No rooms available",
  "날짜 또는 투숙 인원을 바꿔 다시 확인해 주세요.": "Try different dates or guest numbers.",
  "잔여": "Remaining",
  "실": " rooms",
  "성인": "Adults",
  "명": "",
  "아동": "Children",
  "객실": "Rooms",
  "개": "",
  "기준": "",
  "조식 포함": "Breakfast included",
  "박 총액": " nights total",
  "선택": "Select",
  "선택한 객실": "Selected room",
  "선택한 요금제": "Selected rate plan",
  "선택한 객실을 현재 판매하지 않습니다. 객실 검색으로 돌아가 다른 객실을 선택해 주세요.": "This room is no longer available. Return to search and choose another room.",
  "선택한 객실 정보를 불러오지 못했습니다. 객실 검색으로 돌아가 다시 확인해 주세요.": "We could not load this room. Return to search and try again.",
  "예약 관리 정보를 찾을 수 없습니다. 객실 검색부터 다시 진행해 주세요.": "Reservation access is unavailable. Start again from room search.",
  "결제창을 닫았습니다. 확보 시간 안에 다시 시도해 주세요.": "The payment window closed. Retry before the hold expires.",
  "선택한 객실이 없습니다": "No room selected",
  "객실 검색에서 요금제를 선택한 뒤 예약 정보를 입력해 주세요.": "Choose a room and rate plan before entering guest details.",
  "객실 검색으로 돌아가기": "Back to room search",
  "예약 정보를 확인해 주세요": "Review your reservation",
  "결제 전 서버가 객실 재고와 최종 금액을 다시 확인합니다.": "The server checks availability and the final total before payment.",
  "테스트 환경입니다. 실제로 결제되지 않아요.": "Test environment. No real charge will be made.",
  "선택한 객실과 금액을 확인하고 있습니다…": "Checking your selected room and price…",
  "예약자 정보": "Guest details",
  "예약자 이름": "Guest name",
  "이메일": "Email",
  "전화번호": "Phone number",
  "예약 및 결제 서비스 이용 약관과 개인정보 처리에 동의합니다.": "I agree to the booking and payment terms and personal data processing.",
  "예약 및 결제 진행": "Continue to payment",
  "서버에서 객실 재고와 최종 금액을 확인하고 있습니다…": "The server is checking availability and the final total…",
  "객실 다시 검색하기": "Search rooms again",
  "선택한 객실 요약": "Selected room summary",
  "숙박 일정": "Stay dates",
  "투숙 인원": "Guests",
  "총 결제 예정 금액": "Total to pay",
  "박": " nights",
  "세금 포함": "tax included",
  "객실을 확보했습니다": "Your room is on hold",
  "남은 확보 시간": "Hold time remaining",
  "예약자 정보는 잠겨 있습니다. 확보 시간 안에 결제를 완료해 주세요.": "Guest details are locked. Complete payment before the hold expires.",
  "토스 결제창을 여는 중…": "Preparing payment…",
  "테스트 결제 완료하기": "Complete test payment",
  "토스 테스트 결제": "Toss test payment",
  "토스 테스트 키가 설정되지 않아 결제창을 열 수 없습니다. 확보 시간 안에 운영자에게 설정을 요청해 주세요.": "Payment is not configured. Contact the operator before the hold expires.",
  "결제창에서 결제를 완료하지 않았습니다. 같은 객실 확보 건에서 다시 시도할 수 있습니다.": "Payment was not completed. You can retry using the same room hold.",
  "결제 복귀 정보를 확인할 수 없습니다. 중복 결제하지 말고 서버 상태를 확인해 주세요.": "We could not verify the payment return. Check the server status before paying again.",
  "결제 결과를 아직 확인하지 못했습니다. 중복 결제하지 말고 서버 상태를 다시 확인해 주세요.": "The payment result is not yet confirmed. Check the server status before paying again.",
  "서버에서 결제 결과를 확인하고 있습니다.": "Checking the payment result with the server.",
  "확인할 결제 정보가 없습니다": "No payment information available",
  "예약을 진행한 같은 브라우저에서 예약 상태를 다시 확인해 주세요.": "Check your reservation in the browser you used to book.",
  "홈으로": "Home",
  "예약이 확정되었습니다": "Your reservation is confirmed",
  "결제 결과를 확인하고 있습니다": "Checking your payment result",
  "실제 과금 없는 테스트 결제입니다.": "This is a test payment with no real charge.",
  "서버에서 결제 결과를 확인하고 있습니다…": "Checking the payment result with the server…",
  "예약 번호": "Reservation number",
  "객실 수": "Rooms",
  "결제 금액": "Payment total",
  "예약 상세 보기": "View reservation",
  "서버 상태 다시 확인": "Check server status",
  "예약 화면으로 돌아가기": "Back to checkout",
  "결제가 확인되어 예약이 확정되었습니다.": "Payment verified. Your reservation is confirmed.",
  "객실 확보 시간이 만료되었습니다. 객실을 다시 검색해 주세요.": "Your room hold expired. Search rooms again.",
  "결제가 완료되지 않았습니다. 확보 시간 안에 다시 시도하거나 서버 상태를 확인해 주세요.": "Payment was not completed. Retry before the hold expires or check the server status.",
  "결제 결과를 확인하고 있습니다. 중복 결제하지 말고 서버 상태를 다시 확인해 주세요.": "Checking the payment result. Check the server status before paying again.",
  "요금이 변경되었습니다. 최신 객실과 금액을 다시 확인해 주세요.": "The price changed. Check the latest rooms and prices.",
  "선택한 객실이 매진되었습니다. 다른 객실을 다시 선택해 주세요.": "This room sold out. Choose another room.",
  "현재 상태를 확인하지 못했습니다. 입력 내용은 유지되어 있습니다. 잠시 후 다시 시도해 주세요.": "We could not confirm the status. Your details are preserved. Try again shortly.",
  "투숙 인원 선택": "Select guests",
  "만 13세 이상": "Age 13 and over",
  "만 12세 이하": "Age 12 and under",
  "줄이기": "Decrease",
  "늘리기": "Increase",
  "체크인 / 체크아웃": "Check-in / Check-out",
  "숙박 날짜 선택": "Select stay dates",
  "체크인과 체크아웃 날짜를 선택하세요": "Choose check-in and check-out dates",
  "체크아웃 날짜를 선택하세요.": "Choose your check-out date.",
  "선택 버튼을 누르면 날짜가 적용됩니다.": "Select Apply to confirm your dates.",
  "닫기": "Close",
  "지점 선택": "Choose a hotel",
  "여행할 지점": "Your hotel",
  "지점을 선택하세요": "Choose a hotel"
}
export function bookingText(locale: Locale, value: string) { return locale === 'en' ? (english[value] ?? value) : value }
